server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  routes:
    # Frontend calls /aurora-service/** â†’ Backend /seller-center/**
    seller-center:
      path: /aurora-service/**
      url: http://hello-springboot.default.svc.cluster.local:8080
      stripPrefix: true

  # Add prefix /seller-center when forwarding
  prefix: ""
  add-proxy-headers: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes

logging:
  level:
    com.netflix.zuul: DEBUG
